const jCategory = [
    {
        index: 0,
        image: '../images/google.png',
        title: 'Web Developer',
        rate: '$900 3200/m',
        av: 'Full Time',
        companyName: 'Google',
        location: 'USA',
        vacancy: '01',
        hours: '70 / Week',
        description : 'Hello',
        workPlace: 'Work from home',
        education: 'Bachelor degree in any Computer Science courses',
        experience: ' 2 to 7 year(s)'
    },
    {
        index: 1,
        image: '../images/uber.png',
        title: 'Uber',
        rate: '$900 1200/m',
        av: 'Freelancer',
        companyName: 'Uber',
        location: 'USA',
        vacancy: '09',
        hours: '30 / Week',
        description : 'Job description goes here...',
        workPlace: 'Onsite',
        education: 'Bachelor in Car',
        experience: ' 2 to 7 year(s)'
    },
    {
        index: 2,
        image: '../images/linkedin.png',
        title: 'Business Associate',
        rate: '$1000 1700/m',
        av: 'Part Time',
        companyName: 'Linkedin',
        location: 'IRN',
        vacancy: '08',
        hours: '80 / Week',
        description : 'Job description goes here...',
        workPlace: 'Onsite',
        education: 'Bachelor of BBA',
        experience: ' 2 to 4 year(s)'
    },
    {
        index: 3,
        image: '../images/facebook.png',
        title: 'Digital Marketing',
        rate: '$800 1100/m',
        av: 'Full Time',
        companyName: 'Facebook',
        location: 'PAK',
        vacancy: '02',
        hours: '10 / Week',
        description : 'Job description goes here...',
        workPlace: 'Work from home',
        education: 'Bachelor degree in any Computer Science courses',
        experience: ' 1 to 2 year(s)'
    },
    {
        index: 4,
        image: '../images/yahoo.png',
        title: 'User Experience',
        rate: '$1400 1900/m',
        av: 'Part Time',
        companyName: 'Yahoo',
        location: 'AFG',
        vacancy: '04',
        hours: '30 / Week',
        description : 'Job Description goes here...',
        workPlace: 'Onsite',
        education: 'Bachelor degree in any Computer Science courses',
        experience: ' 2 to 3 year(s)'
    },
]